---
abstract: 'Rinci/Riap-based web application framework'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Module::Build: 0.3601
  Perinci::Examples: 0
  Test::More: 0.96
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300002, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perinci-Web
requires:
  Riap: 1.1.0
  Rinci: 1.1.0
  perl: 5.010000
resources:
  homepage: http://metacpan.org/dist/Perinci-Web
  repository: http://github.com/sharyanto/perl-Perinci-Web
version: 0.00
